export const ADD_ARTICLE = 'ADD_ARTICLE';
export const REMOVE_ARTICLE = 'REMOVE_ARTICLE';
export const GET_USERS = 'GET_USERS';
export const LIST_USERS = 'LIST_USERS';
export const FETCH_USERS = 'FETCH_USERS';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS';
export const FETCH_USER_STARTING = 'FETCH_USER_STARTING';